In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [121]:
np.log2(36)
np.exp2(5)

np.float64(32.0)

In [122]:
np.cos(np.pi * 4)
np.sin(np.pi)

np.float64(1.2246467991473532e-16)

In [123]:
random_number = np.random.rand(100)
random_number.min()
random_number.max()
random_number.mean()

#https://numpy.org/doc/stable/

np.float64(0.4543654356440247)

In [194]:
arrd_1 = np.array([1,2,3,4,5,6]) # 1D - vector
arrd_2 = np.array([[1,2,3,4,5,6], [2,2,3,4,5,6]]) # 2D - matrix
arrd_3 = np.array([[1,2,3,4,5], [2,2,3,4,5], [3,4,6,7,8]]) # 2D - matrix
arrd_4 = np.array([[[1,2,3,4,5], [2,2,3,4,5]], [[2,2,3,4,5], [3,4,6,7,8]]]) # 3D - tensor
arrd_5 = np.array([[[[1,2,3,4,5], [2,2,3,4,5], [2,2,3,4,5]],[[1,2,3,4,5], [2,2,3,4,5], [2,2,3,4,5]]], [[[2,2,3,4,5], [2,2,3,4,5], [3,4,6,7,8]],[[2,2,3,4,5], [2,2,3,4,5], [3,4,6,7,8]]]]) # ND - n dimensional
print(arrd_1.ndim)
print(arrd_2.ndim)
print(arrd_3.ndim)
print(arrd_4.ndim)
print(arrd_5.ndim)
print(arrd_1.shape)
print(arrd_2.shape)
print(arrd_3.shape)
print(arrd_4.shape)
print(arrd_5.shape)
arrd_1.size
arrd_3.size == np.prod(arrd_3.shape)
arrd_1.dtype



1
2
2
3
4
(6,)
(2, 6)
(3, 5)
(2, 2, 5)
(2, 2, 3, 5)


dtype('int64')

In [158]:
vec_1 = arrd_1.reshape(3,2) #1st is row, 2nd column - creating 2D array from 1D array
vec_1.shape
vec_1.ndim

2

In [192]:
a = np.zeros(4) # creating 4 zeros
b = np.ones(5) # creating 5 ones
c = np.empty(3) # creating 3 random
d = np.arange(8) # creating 8 sequent number starting from 0 excluding 8
e = np.arange(0,20,1) # 0 starting point, 20 until and excluding, 1 step
f = np.linspace(0, 15, num=9) # 0 starting point, 15 including, 9 is in how many step
g = np.linspace(0, 15, num=9, dtype=np.int64) # possible to define data type
f.dtype


dtype('float64')

In [201]:
tensor_1 = arrd_2.reshape(2,3,2) # to create from 2D - into 3D array
tensor_1

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[2, 2],
        [3, 4],
        [5, 6]]])

In [240]:
random_1 = np.arange(27).reshape(3,3,3) #creating 3D array
random_1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [259]:
t_pose = arrd_2.reshape(3,4).T # transposing
t_pose


array([[1, 5, 3],
       [2, 6, 4],
       [3, 2, 5],
       [4, 2, 6]])

In [273]:
t_pose[:]
t_pose[0:4, 1:3]
t_pose[2:3, 1:2]

array([[2]])

In [311]:
np.random.seed(100) # every seed number will give certain number that not changing every load
random_n = (100 * np.random.rand(3)).round(0)
random_n

array([54., 28., 42.])

In [21]:
pand = pd.Series({"hey": "oh", "hol": "to"})
pand

  
# https://pandas.pydata.org/docs/getting_started/index.html#getting-started

0
hey  oh
hol  to

In [23]:
os.getcwd()


'c:\\Users\\User\\Desktop\\PORTFOLIO\\python_statistics'

In [24]:
os.chdir?

Signature: os.chdir(path)
Docstring:
Change the current working directory to the specified path.

path may always be specified as a string.
On some platforms, path may also be specified as an open file descriptor.
  If this functionality is unavailable, using it raises an exception.
Type:      builtin_function_or_method

In [16]:
model = pd.Series(['Hyundai', 'Toyota', 'BMW'])
year = pd.Series(['2012', '2013', '2014'])
host_dis = pd.DataFrame({'model': model, 'year': year}, columns=['model', 'year'])
host_dis


model  year
0  Hyundai  2012
1   Toyota  2013
2      BMW  2014

In [25]:
data = {'country': ['China', 'USA', 'UK'],
        'year': [2012, 2013, 2018]}

world_visited = pd.DataFrame(data)
world_visited = pd.DataFrame(data, columns=['year', 'country'])
world_visited

year country
0  2012   China
1  2013     USA
2  2018      UK

In [41]:
data = pd.read_csv('data_analysis/sources/Unicorn-companies.csv')
data.head()
data.City
data.shape
data.tail()
data['Continent']
data[0:2]
data.City[0:1]
data.dtypes
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Company           1074 non-null   object
 1   Valuation         1074 non-null   int64 
 2   Date Joined       1074 non-null   object
 3   Industry          1074 non-null   object
 4   City              1057 non-null   object
 5   Country/Region    1074 non-null   object
 6   Continent         1074 non-null   object
 7   Year Founded      1074 non-null   int64 
 8   Funding           1074 non-null   object
 9   Select Investors  1074 non-null   object
dtypes: int64(2), object(8)
memory usage: 84.0+ KB


In [44]:
data.iloc[[0,1,2,5,7], [2,3,5]]   # index location 1st => rows 2nd => columns

Date Joined                             Industry Country/Region
0  2017-04-07              Artificial intelligence          China
1  2012-12-01                                Other  United States
2  2018-07-03      E-commerce & direct-to-consumer          China
5  2018-01-08         Internet software & services      Australia
7  2014-12-30  Supply chain, logistics, & delivery  United States

In [47]:
data.loc[[0,1,2,5,7], ['Date Joined', 'Industry', 'Country/Region']]   # location 1st => rows 2nd => columns by name

Date Joined                             Industry Country/Region
0  2017-04-07              Artificial intelligence          China
1  2012-12-01                                Other  United States
2  2018-07-03      E-commerce & direct-to-consumer          China
5  2018-01-08         Internet software & services      Australia
7  2014-12-30  Supply chain, logistics, & delivery  United States

In [60]:
[data['Country/Region'] == 'China']
data[data['Country/Region'] == 'China']

Company  Valuation Date Joined  \
0        Bytedance        180  2017-04-07   
2            SHEIN        100  2018-07-03   
17     Xiaohongshu         20  2016-03-31   
19       Yuanfudao         17  2017-05-31   
22    Genki Forest         15  2020-03-01   
...            ...        ...         ...   
1066     YH Global          1  2017-09-21   
1068    Yunxuetang          1  2021-03-29   
1069      Zhaogang          1  2017-06-29   
1070   Zhuan Zhuan          1  2017-04-18   
1071      Zihaiguo          1  2021-05-06   

                                 Industry       City Country/Region Continent  \
0                 Artificial intelligence    Beijing          China      Asia   
2         E-commerce & direct-to-consumer   Shenzhen          China      Asia   
17        E-commerce & direct-to-consumer   Shanghai          China      Asia   
19                                 Edtech    Beijing          China      Asia   
22                      Consumer & retail    Beijing          China      Asia   
...                                   ...        ...            ...       ...   
1066  Supply chain, logistics, & delivery   Shenzhen          China      Asia   
1068                               Edtech     Suzhou          China      Asia   
1069      E-commerce & direct-to-consumer   Shanghai          China      Asia   
1070      E-commerce & direct-to-consumer    Beijing          China      Asia   
1071                    Consumer & retail  Chongqing          China      Asia   

      Year Founded Funding                                   Select Investors  
0             2012     $8B  Sequoia Capital China, SIG Asia Investments, S...  
2             2008     $2B  Tiger Global Management, Sequoia Capital China...  
17            2013   $918M                     GGV Capital, ZhenFund, Tencent  
19            2012     $4B       Tencent Holdings, Warbug Pincus, IDG Capital  
22            2016   $721M  Sequoia Capital China, Longfor Capitalm, Gaoro...  
...            ...     ...                                                ...  
1066          1997   $182M                       Co-Energy Finance, Grandland  
1068          2011   $389M  Matrix Partners China, Sequoia Capital China, ...  
1069          2012   $379M    K2 Ventures, Matrix Partners China, IDG Capital  
1070          2015   $990M                           58.com, Tencent Holdings  
1071          2018    $80M  Xingwang Investment Management, China Capital ...  

[173 rows x 10 columns]

In [82]:
# Method 1
data.Valuation[data['Country/Region'] == 'China']

# Method 2
data[data['Country/Region'] == 'China'].Valuation

# Method 3
data.loc[data['Country/Region'] == 'China', 'Valuation']

0       180
2       100
17       20
19       17
22       15
       ... 
1066      1
1068      1
1069      1
1070      1
1071      1
Name: Valuation, Length: 173, dtype: int64

In [84]:
data.loc[data['Country/Region'] == 'China', ['Continent', 'Valuation', 'City']]

Continent  Valuation       City
0         Asia        180    Beijing
2         Asia        100   Shenzhen
17        Asia         20   Shanghai
19        Asia         17    Beijing
22        Asia         15    Beijing
...        ...        ...        ...
1066      Asia          1   Shenzhen
1068      Asia          1     Suzhou
1069      Asia          1   Shanghai
1070      Asia          1    Beijing
1071      Asia          1  Chongqing

[173 rows x 3 columns]

In [10]:
movies = pd.read_csv('data_analysis/sources/Movies.csv')
movies.describe().T

count         mean        std      min      25%      50%  \
Year        5275.0  2010.899526   4.842039  2001.00  2007.00  2012.00   
Duration    5275.0    95.235261  12.771222    46.00    87.00    93.00   
Rating      5275.0     5.379981   1.248103     1.10     4.60     5.50   
Popularity  5275.0    50.009486  28.870229     0.05    25.03    50.02   

                 75%     max  
Year        2015.000  2018.0  
Duration     101.000   219.0  
Rating         6.300     9.7  
Popularity    75.005   100.0